/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachesCornerRouteImport } from './routes/coaches-corner'
import { Route as CoachTrainingRouteImport } from './routes/coach-training'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R7PillarsRouteImport } from './routes/7-pillars'
import { Route as R1On1ProgramRouteImport } from './routes/1-on-1-program'
import { Route as IndexRouteImport } from './routes/index'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesCornerRoute = CoachesCornerRouteImport.update({
  id: '/coaches-corner',
  path: '/coaches-corner',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachTrainingRoute = CoachTrainingRouteImport.update({
  id: '/coach-training',
  path: '/coach-training',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R7PillarsRoute = R7PillarsRouteImport.update({
  id: '/7-pillars',
  path: '/7-pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const R1On1ProgramRoute = R1On1ProgramRouteImport.update({
  id: '/1-on-1-program',
  path: '/1-on-1-program',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1-on-1-program': typeof R1On1ProgramRoute
  '/7-pillars': typeof R7PillarsRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/coach-training': typeof CoachTrainingRoute
  '/coaches-corner': typeof CoachesCornerRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1-on-1-program': typeof R1On1ProgramRoute
  '/7-pillars': typeof R7PillarsRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/coach-training': typeof CoachTrainingRoute
  '/coaches-corner': typeof CoachesCornerRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1-on-1-program': typeof R1On1ProgramRoute
  '/7-pillars': typeof R7PillarsRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/coach-training': typeof CoachTrainingRoute
  '/coaches-corner': typeof CoachesCornerRoute
  '/contact': typeof ContactRoute
  '/podcast': typeof PodcastRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/1-on-1-program'
    | '/7-pillars'
    | '/about'
    | '/blog'
    | '/booking'
    | '/coach-training'
    | '/coaches-corner'
    | '/contact'
    | '/podcast'
    | '/services'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/1-on-1-program'
    | '/7-pillars'
    | '/about'
    | '/blog'
    | '/booking'
    | '/coach-training'
    | '/coaches-corner'
    | '/contact'
    | '/podcast'
    | '/services'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/1-on-1-program'
    | '/7-pillars'
    | '/about'
    | '/blog'
    | '/booking'
    | '/coach-training'
    | '/coaches-corner'
    | '/contact'
    | '/podcast'
    | '/services'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1On1ProgramRoute: typeof R1On1ProgramRoute
  R7PillarsRoute: typeof R7PillarsRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BookingRoute: typeof BookingRoute
  CoachTrainingRoute: typeof CoachTrainingRoute
  CoachesCornerRoute: typeof CoachesCornerRoute
  ContactRoute: typeof ContactRoute
  PodcastRoute: typeof PodcastRoute
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches-corner': {
      id: '/coaches-corner'
      path: '/coaches-corner'
      fullPath: '/coaches-corner'
      preLoaderRoute: typeof CoachesCornerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-training': {
      id: '/coach-training'
      path: '/coach-training'
      fullPath: '/coach-training'
      preLoaderRoute: typeof CoachTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/7-pillars': {
      id: '/7-pillars'
      path: '/7-pillars'
      fullPath: '/7-pillars'
      preLoaderRoute: typeof R7PillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1-on-1-program': {
      id: '/1-on-1-program'
      path: '/1-on-1-program'
      fullPath: '/1-on-1-program'
      preLoaderRoute: typeof R1On1ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1On1ProgramRoute: R1On1ProgramRoute,
  R7PillarsRoute: R7PillarsRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookingRoute: BookingRoute,
  CoachTrainingRoute: CoachTrainingRoute,
  CoachesCornerRoute: CoachesCornerRoute,
  ContactRoute: ContactRoute,
  PodcastRoute: PodcastRoute,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
